player_x:     BLOCK 1
player_state: BLOCK 1

_PLAYER_STATE_ACTIVE_VALUE:             EQU 0b00000001
_PLAYER_STATE_EXPLODING_VALUE:          EQU 0b00000010
_PLAYER_STATE_DONE_EXPLODING_VALUE:     EQU 0b00000100


_PLAYER_STATE_ACTIVE_BIT:               EQU 0
_PLAYER_STATE_EXPLODING_BIT:            EQU 1
_PLAYER_STATE_DONE_EXPLODING_BIT:       EQU 2

_PLAYER_EXPLOSION_VARIANT_SWITCH_MAX:   EQU 2
_player_explosion_variant_cycle_count:  BLOCK 1
_player_explosion_variant_sprite:       BLOCK 2

