player_x:     BLOCK 1
player_state: BLOCK 1

_PLAYER_STATE_ACTIVE_VALUE:             EQU 0b00000001
_PLAYER_STATE_HIT_VALUE:                EQU 0b00000010
_PLAYER_STATE_EXPLODING_VALUE:          EQU 0b00000100
_PLAYER_STATE_DONE_EXPLODING_VALUE:     EQU 0b00001000


_PLAYER_STATE_ACTIVE_BIT:               EQU 0
_PLAYER_STATE_HIT_BIT:                  EQU 1
_PLAYER_STATE_EXPLODING_BIT:            EQU 2
_PLAYER_STATE_DONE_EXPLODING_BIT:       EQU 3

_player_explosion_current_variant_toggle: BLOCK 1
_player_explosion_current_variant_sprite: BLOCK 2

; _PLAYER_EXPLOSION_VARIANT_0_SPRITE:     EQU 0
; _PLAYER_EXPLOSION_VARIANT_1_SPRITE:     EQU 1
; _PLAYER_EXPLOSION_VARIANT_SPRITE_COUNT: EQU 2

; _PLAYER_EXPLOSION_VARIANT_LOOKUP:       WORD sprites.PLAYER_EXPLOSION_VARIANT_0, sprites.PLAYER_EXPLOSION_VARIANT_1
