_VTRACE_INTERVAL:   EQU 5
_vtrace_count:      BLOCK 1
_VTRACE_BYTE:       EQU memory_map.SCREEN_ATTR_START+(draw_common.SCREEN_HEIGHT_CHARS-1)*draw_common.SCREEN_WIDTH_CHARS

_CYCLE_BYTE: EQU _VTRACE_BYTE+1