; Offsets into structure representing an alien
STATE_OFFSET_DRAW_COORDS:               EQU 0           ; Coords
STATE_OFFSET_DRAW_COORDS_Y:             EQU STATE_OFFSET_DRAW_COORDS
STATE_OFFSET_DRAW_COORDS_X:             EQU STATE_OFFSET_DRAW_COORDS+1
STATE_OFFSET_VAR_0_SPRITE:              EQU 2           ; First variant sprite
STATE_OFFSET_VAR_1_SPRITE:              EQU 4           ; Second variant sprite
STATE_OFFSET_STATE:                     EQU 6           ; Status of sprite from _ALIEN_STATE_* values
STATE_OFFSET_VARIANT:                   EQU 7           ; Current sprite variant from _ALIEN_VARIANT_? values
STATE_OFFSET_TYPE:                      EQU 8           ; Alien type from _ALIEN_TYPE_? values

_AS_SIZE:                               EQU 9           ; Size of the alien sprite structure

; Status of an alien
_ALIEN_STATE_NEW_VALUE:                 EQU 0b00000001  ; Just created
_ALIEN_STATE_ACTIVE_VALUE:              EQU 0b00000010  ; Normally active alien
_ALIEN_STATE_DEAD_VALUE:                EQU 0b00000100  ; Dead alien

_ALIEN_STATE_NEW_BIT:                   EQU 0
_ALIEN_STATE_ACTIVE_BIT:                EQU 1
_ALIEN_STATE_DEAD_BIT:                  EQU 2

; Alien variant for walking animation
_ALIEN_VARIANT_0_VALUE:                 EQU 0b00000001
_ALIEN_VARIANT_1_VALUE:                 EQU 0b00000010

_ALIEN_VARIANT_0_BIT:                   EQU 0
_ALIEN_VARIANT_1_BIT:                   EQU 1

; Alien types
_ALIEN_TYPE_0:                          EQU 0
_ALIEN_TYPE_1:                          EQU 1
_ALIEN_TYPE_2:                          EQU 2

_alien_pack_moving:                     BLOCK 1
_alien_is_exploding:                    BLOCK 1
_exploding_alien:                       BLOCK 2

; Current number of aliens
alien_count:                            BLOCK 1

; Lookup table into _alien_state table
_ALIEN_LOOKUP:
    ; Row 0 (bottom of pack)
    WORD _aliens+_AS_SIZE*0, _aliens+_AS_SIZE*1, _aliens+_AS_SIZE*2, _aliens+_AS_SIZE*3, _aliens+_AS_SIZE*4 
    WORD _aliens+_AS_SIZE*5, _aliens+_AS_SIZE*6, _aliens+_AS_SIZE*7, _aliens+_AS_SIZE*8, _aliens+_AS_SIZE*9, _aliens+_AS_SIZE*10
    ; Row 1
    WORD _aliens+_AS_SIZE*11, _aliens+_AS_SIZE*12, _aliens+_AS_SIZE*13, _aliens+_AS_SIZE*14, _aliens+_AS_SIZE*15
    WORD _aliens+_AS_SIZE*16, _aliens+_AS_SIZE*17, _aliens+_AS_SIZE*18, _aliens+_AS_SIZE*19, _aliens+_AS_SIZE*20,_aliens+_AS_SIZE*21
    ; Row 2
    WORD _aliens+_AS_SIZE*22, _aliens+_AS_SIZE*23, _aliens+_AS_SIZE*24, _aliens+_AS_SIZE*25, _aliens+_AS_SIZE*26 
    WORD _aliens+_AS_SIZE*27, _aliens+_AS_SIZE*28, _aliens+_AS_SIZE*29, _aliens+_AS_SIZE*30, _aliens+_AS_SIZE*31, _aliens+_AS_SIZE*32
    ; Row 3
    WORD _aliens+_AS_SIZE*33, _aliens+_AS_SIZE*34, _aliens+_AS_SIZE*35, _aliens+_AS_SIZE*36, _aliens+_AS_SIZE*37 
    WORD _aliens+_AS_SIZE*38, _aliens+_AS_SIZE*39, _aliens+_AS_SIZE*40, _aliens+_AS_SIZE*41, _aliens+_AS_SIZE*42, _aliens+_AS_SIZE*43  
    ; Row 4
    WORD _aliens+_AS_SIZE*44, _aliens+_AS_SIZE*45, _aliens+_AS_SIZE*46, _aliens+_AS_SIZE*47, _aliens+_AS_SIZE*48 
    WORD _aliens+_AS_SIZE*49, _aliens+_AS_SIZE*50, _aliens+_AS_SIZE*51, _aliens+_AS_SIZE*52, _aliens+_AS_SIZE*53, _aliens+_AS_SIZE*54

; Number of aliens in total in new pack
_ALIEN_PACK_SIZE:                       EQU ($-_ALIEN_LOOKUP)/2
_ALIEN_PACK_ROW_COUNT:                  EQU 5
_ALIEN_PACK_COLUMN_COUNT:               EQU 11

; Initialization values for a new sheet of aliens
_ALIENS_INIT:
    ; Bottom row - Row 0
    WORD 0x1060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x2060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x3060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x4060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x5060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x6060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x7060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x8060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x9060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0xA060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0xB060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0

    ; Row 1
    WORD 0x1050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x2050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x3050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x4050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x5050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x6050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x7050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x8050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0x9050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0xA050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    WORD 0xB050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_0
    
    ; Row 2
    WORD 0x1040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x2040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x3040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x4040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x5040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x6040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x7040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x8040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x9040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0xA040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0xB040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1

    ; Row 3
    WORD 0x1030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x2030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x3030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x4030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x5030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x6030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x7030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x8030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0x9030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0xA030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1
    WORD 0xB030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_1

    ; Row 4
    WORD 0x1020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0x2020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0x3020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0x4020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0x5020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0x6020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0x7020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0x8020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0x9020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0xA020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2
    WORD 0xB020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1
    BYTE _ALIEN_STATE_NEW_VALUE,_ALIEN_VARIANT_0_VALUE,_ALIEN_TYPE_2

; Size of the aliens array in bytes
_ALIENS_SIZE:  EQU $-_ALIENS_INIT

; Current sheet of aliens
_aliens: BLOCK _ALIENS_SIZE

; Y offsets to start alien pack (based on sheet number)
_aliens_adjust_index: BLOCK 1                                                   ; Current index into alien offsets

_ALIENS_ADJUST_FOR_SHEET: BYTE 0x00,0x08,0x10,0x18,0x18,0x18,0x20,0x20,0x28     ; Y offsets 

_ALIENS_ADJUST_FOR_SHEET_COUNT: EQU $-_ALIENS_ADJUST_FOR_SHEET                  ; Number of Y offsets