BOTTOM_GEL_TOP_LEFT_Y:          EQU draw_common.SCREEN_HEIGHT_CHARS-6
BOTTOM_GEL_HEIGHT:              EQU 5
BASES_GEL_TOP_LEFT_X:           EQU RESERVE_BASE_START_X/8
BASES_GEL_TOP_LEFT_Y:           EQU draw_common.SCREEN_HEIGHT_CHARS-1
BASES_GEL_WIDTH:                EQU 10
BASES_GEL_HEIGHT:               EQU 1
SPACESHIP_GEL_LEFT_Y:           EQU 2
SPACESHIP_GEL_HEIGHT:           EQU 1