PLAYER_COUNT_CHAR_X:            EQU INSET_X_CHARS+1
PLAYER_COUNT_CHAR_Y:            EQU screen.SCREEN_HEIGHT_CHARS-1
PLAYER_COUNT_CHAR_COORDS:       EQU (PLAYER_COUNT_CHAR_X<<8) + PLAYER_COUNT_CHAR_Y

; Reserve bases
RESERVE_BASE_Y:                 EQU screen.SCREEN_HEIGHT_PIXELS-8-1
RESERVE_BASE_START_X:           EQU layout.INSET_X_PIXELS+3*8
RESERVE_BASE_OFFSET_X:          EQU ((sprites.PLAYER_DIM_X_BYTES-1)*8)
