; Player 1 score
SCORE_PLAYER_1_CHAR_X:          EQU INSET_X_CHARS+3
SCORE_PLAYER_1_CHAR_Y:          EQU 1

SCORE_PLAYER_1_CHAR_COORDS:     EQU (SCORE_PLAYER_1_CHAR_X<<8) + SCORE_PLAYER_1_CHAR_Y

; Player 2 score
SCORE_PLAYER_2_CHAR_X:          EQU INSET_X_CHARS+21
SCORE_PLAYER_2_CHAR_Y:          EQU 1
SCORE_PLAYER_2_CHAR_COORDS:     EQU (SCORE_PLAYER_2_CHAR_X<<8) + SCORE_PLAYER_2_CHAR_Y

; High score
SCORE_HIGH_CHAR_X:              EQU INSET_X_CHARS+11
SCORE_HIGH_CHAR_Y:              EQU 1
SCORE_HIGH_CHAR_COORDS:         EQU (SCORE_HIGH_CHAR_X<<8) + SCORE_HIGH_CHAR_Y