SHIELD_WIDTH_PIXELS:            EQU (sprites.SHIELD_DIM_X_BYTES-1)*8

SHIELD_1_X:                     EQU SCREEN_X_MIDDLE-3*SHIELD_WIDTH_PIXELS-SHIELD_WIDTH_PIXELS/2
SHIELD_2_X:                     EQU SCREEN_X_MIDDLE-1*SHIELD_WIDTH_PIXELS-SHIELD_WIDTH_PIXELS/2
SHIELD_3_X:                     EQU SCREEN_X_MIDDLE+1*SHIELD_WIDTH_PIXELS-SHIELD_WIDTH_PIXELS/2
SHIELD_4_X:                     EQU SCREEN_X_MIDDLE+3*SHIELD_WIDTH_PIXELS-SHIELD_WIDTH_PIXELS/2
SHIELD_Y:                       EQU draw_common.SCREEN_HEIGHT_PIXELS-6*8