; This file was automatically generated, DO NOT MODIFY

	INCLUDE "sprites/mask_1x4.asm"
	INCLUDE "sprites/mask_2x8.asm"
	INCLUDE "sprites/mask_player_bullet.asm"
	INCLUDE "sprites/sprite_alien_1_variant_0.asm"
	INCLUDE "sprites/sprite_alien_1_variant_1.asm"
	INCLUDE "sprites/sprite_alien_2_variant_0.asm"
	INCLUDE "sprites/sprite_alien_2_variant_1.asm"
	INCLUDE "sprites/sprite_alien_3_variant_0.asm"
	INCLUDE "sprites/sprite_alien_3_variant_1.asm"
	INCLUDE "sprites/sprite_base.asm"
	INCLUDE "sprites/sprite_blank_1b_x_4px.asm"
	INCLUDE "sprites/sprite_blank_1b_x_8px.asm"
	INCLUDE "sprites/sprite_blank_2b_x_8px.asm"
	INCLUDE "sprites/sprite_player_bullet.asm"
	INCLUDE "sprites/sprite_player_bullet_explosion.asm"
	INCLUDE "sprites/sprite_shield.asm"
