; Offsets into structure representing an alien
_STATE_OFFSET_DRAW_COORDS:              EQU 0           ; Coords
_STATE_OFFSET_DRAW_COORDS_Y:            EQU _STATE_OFFSET_DRAW_COORDS
_STATE_OFFSET_DRAW_COORDS_X:            EQU _STATE_OFFSET_DRAW_COORDS+1
_STATE_OFFSET_VAR_0_SPRITE:             EQU 2           ; First variant sprite
_STATE_OFFSET_VAR_1_SPRITE:             EQU 4           ; Second variant sprite
_STATE_OFFSET_VAR_0_BLANK:              EQU 6           ; First variant blank
_STATE_OFFSET_VAR_1_BLANK:              EQU 8           ; Second variant blank
_STATE_OFFSET_STATE:                    EQU 10          ; Status of sprite from _ALIEN_STATE_* values
_STATE_OFFSET_VARIANT:                  EQU 11
_STATE_OFFSET_TYPE:                     EQU 12

_AS_SIZE:                               EQU 13          ; Size of the alien sprite structure

; Status of an alien
_ALIEN_STATE_NEW:                       EQU 0b00000001  ; Just created
_ALIEN_STATE_ACTIVE:                    EQU 0b00000010  ; Normally active alien
_ALIEN_STATE_DEAD:                      EQU 0b00000100  ; Dead alien

_ALIEN_STATE_NEW_BIT:                   EQU 0
_ALIEN_STATE_ACTIVE_BIT:                EQU 1
_ALIEN_STATE_DEAD_BIT:                  EQU 2

; Current alien variant for walking animation
_ALIEN_VARIANT_0:                       EQU 0b00000001
_ALIEN_VARIANT_1:                       EQU 0b00000010

_ALIEN_VARIANT_0_BIT:                   EQU 0
_ALIEN_VARIANT_1_BIT:                   EQU 1

; Alien pack as per _STATE_OFFSET_* constants
_alien_state:
    ; Bottom row - Row 0
    WORD 0x1060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x2060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x3060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x4060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x5060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x6060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x7060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x8060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x9060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0xA060,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0

    ; Row 1
    WORD 0x1050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x2050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x3050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x4050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x5050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x6050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x7050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x8050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0x9050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    WORD 0xA050,sprites.ALIEN_0_VARIANT_0,sprites.ALIEN_0_VARIANT_1,sprites.ALIEN_0_VARIANT_0_BLANK,sprites.ALIEN_0_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_0
    
    ; Row 2
    WORD 0x1040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x2040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x3040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x4040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x5040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x6040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x7040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x8040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x9040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0xA040,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1

    ; Row 3
    WORD 0x1030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x2030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x3030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x4030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x5030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x6030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x7030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x8030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0x9030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1
    WORD 0xA030,sprites.ALIEN_1_VARIANT_0,sprites.ALIEN_1_VARIANT_1,sprites.ALIEN_1_VARIANT_0_BLANK,sprites.ALIEN_1_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_1

    ; Row 4
    WORD 0x1020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2
    WORD 0x2020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2
    WORD 0x3020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2
    WORD 0x4020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2
    WORD 0x5020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2
    WORD 0x6020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2
    WORD 0x7020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2
    WORD 0x8020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2
    WORD 0x9020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2
    WORD 0xA020,sprites.ALIEN_2_VARIANT_0,sprites.ALIEN_2_VARIANT_1,sprites.ALIEN_2_VARIANT_0_BLANK,sprites.ALIEN_2_VARIANT_1_BLANK
    BYTE _ALIEN_STATE_NEW,_ALIEN_VARIANT_0,scoring.ALIEN_TYPE_2

; Lookup table into _alien_state table
_ALIEN_LOOKUP:
    ; Row 0 (bottom of pack)
    WORD _alien_state+_AS_SIZE*0, _alien_state+_AS_SIZE*1, _alien_state+_AS_SIZE*2, _alien_state+_AS_SIZE*3, _alien_state+_AS_SIZE*4 
    WORD _alien_state+_AS_SIZE*5, _alien_state+_AS_SIZE*6, _alien_state+_AS_SIZE*7, _alien_state+_AS_SIZE*8, _alien_state+_AS_SIZE*9
    ; Row 1
    WORD _alien_state+_AS_SIZE*10, _alien_state+_AS_SIZE*11, _alien_state+_AS_SIZE*12, _alien_state+_AS_SIZE*13, _alien_state+_AS_SIZE*14 
    WORD _alien_state+_AS_SIZE*15, _alien_state+_AS_SIZE*16, _alien_state+_AS_SIZE*17, _alien_state+_AS_SIZE*18, _alien_state+_AS_SIZE*19
    ; Row 2
    WORD _alien_state+_AS_SIZE*20, _alien_state+_AS_SIZE*21, _alien_state+_AS_SIZE*22, _alien_state+_AS_SIZE*23, _alien_state+_AS_SIZE*24 
    WORD _alien_state+_AS_SIZE*25, _alien_state+_AS_SIZE*26, _alien_state+_AS_SIZE*27, _alien_state+_AS_SIZE*28, _alien_state+_AS_SIZE*29
    ; Row 3
    WORD _alien_state+_AS_SIZE*30, _alien_state+_AS_SIZE*31, _alien_state+_AS_SIZE*32, _alien_state+_AS_SIZE*33, _alien_state+_AS_SIZE*34 
    WORD _alien_state+_AS_SIZE*35, _alien_state+_AS_SIZE*36, _alien_state+_AS_SIZE*37, _alien_state+_AS_SIZE*38, _alien_state+_AS_SIZE*39  
    ; Row 4
    WORD _alien_state+_AS_SIZE*40, _alien_state+_AS_SIZE*41, _alien_state+_AS_SIZE*42, _alien_state+_AS_SIZE*43, _alien_state+_AS_SIZE*44 
    WORD _alien_state+_AS_SIZE*45, _alien_state+_AS_SIZE*46, _alien_state+_AS_SIZE*47, _alien_state+_AS_SIZE*48, _alien_state+_AS_SIZE*49

; Number of aliens in total in new pack
_ALIEN_PACK_SIZE:                       EQU ($-_ALIEN_LOOKUP)/2