_SAUCER_STATE_NO_SAUCER_VALUE:          EQU 0b00000001
_SAUCER_STATE_ACTIVE_VALUE:             EQU 0b00000010
_SAUCER_STATE_EXPLODING_VALUE:          EQU 0b00000100
_SAUCER_STATE_DONE_EXPLODING_VALUE:     EQU 0b00001000

_SAUCER_STATE_NO_SAUCER_BIT:            EQU 0
_SAUCER_STATE_ACTIVE_BIT:               EQU 1
_SAUCER_STATE_EXPLODING_BIT:            EQU 2
_SAUCER_STATE_DONE_EXPLODING_BIT:       EQU 3

_saucer_state:                          BLOCK 1
saucer_x:                               BLOCK 1